apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solidarytech-root
  namespace: {{ .Release.Namespace }}
spec:
  project: default
  source:
    repoURL: {{ required "repoURL e obrigatorio" .Values.repoURL | quote }}
    targetRevision: {{ .Values.targetRevision | quote }}
    path: {{ .Values.path | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
