apiVersion: v1
kind: Secret
metadata:
  name: solidarytech-secrets
  namespace: solidarytech
type: Opaque
stringData:
  NGO_DATABASE_URL: REPLACE_ME
  DONATION_DATABASE_URL: REPLACE_ME
  REDIS_ADDR: REPLACE_ME
  AWS_SQS_URL: REPLACE_ME
